kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.config.peer}}.{{ .Values.config.hostname }}.storage.pvc
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
