// Code generated by protoc-gen-go. DO NOT EDIT.
// source: asset.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Asset struct {
	UniqueID             string   `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	Size                 string   `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785e5163229d617, []int{0}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *Asset) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Asset) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Asset) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AssetInput struct {
	Size                 string   `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetInput) Reset()         { *m = AssetInput{} }
func (m *AssetInput) String() string { return proto.CompactTextString(m) }
func (*AssetInput) ProtoMessage()    {}
func (*AssetInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785e5163229d617, []int{1}
}

func (m *AssetInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetInput.Unmarshal(m, b)
}
func (m *AssetInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetInput.Marshal(b, m, deterministic)
}
func (m *AssetInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetInput.Merge(m, src)
}
func (m *AssetInput) XXX_Size() int {
	return xxx_messageInfo_AssetInput.Size(m)
}
func (m *AssetInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetInput.DiscardUnknown(m)
}

var xxx_messageInfo_AssetInput proto.InternalMessageInfo

func (m *AssetInput) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *AssetInput) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AssetInput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AssetFilter struct {
	UniqueID             string   `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetFilter) Reset()         { *m = AssetFilter{} }
func (m *AssetFilter) String() string { return proto.CompactTextString(m) }
func (*AssetFilter) ProtoMessage()    {}
func (*AssetFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4785e5163229d617, []int{2}
}

func (m *AssetFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetFilter.Unmarshal(m, b)
}
func (m *AssetFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetFilter.Marshal(b, m, deterministic)
}
func (m *AssetFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetFilter.Merge(m, src)
}
func (m *AssetFilter) XXX_Size() int {
	return xxx_messageInfo_AssetFilter.Size(m)
}
func (m *AssetFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AssetFilter proto.InternalMessageInfo

func (m *AssetFilter) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func init() {
	proto.RegisterType((*Asset)(nil), "model.Asset")
	proto.RegisterType((*AssetInput)(nil), "model.AssetInput")
	proto.RegisterType((*AssetFilter)(nil), "model.AssetFilter")
}

func init() { proto.RegisterFile("asset.proto", fileDescriptor_4785e5163229d617) }

var fileDescriptor_4785e5163229d617 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0x2e, 0x4e,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x4a,
	0xe6, 0x62, 0x75, 0x04, 0x89, 0x0a, 0x49, 0x71, 0x71, 0x94, 0xe6, 0x65, 0x16, 0x96, 0xa6, 0x7a,
	0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x42, 0x5c, 0x2c, 0xc5, 0x99,
	0x55, 0xa9, 0x12, 0x4c, 0x60, 0x71, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0xbf, 0x3c, 0x2f, 0xb5,
	0x48, 0x82, 0x19, 0x2c, 0x08, 0xe1, 0x80, 0x44, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x58, 0x20,
	0xa2, 0x60, 0x8e, 0x92, 0x0f, 0x17, 0x17, 0xd8, 0x12, 0xcf, 0xbc, 0x82, 0xd2, 0x12, 0x8a, 0x4d,
	0xd3, 0xe4, 0xe2, 0x06, 0x9b, 0xe6, 0x96, 0x99, 0x53, 0x92, 0x5a, 0x84, 0xcf, 0xe1, 0x4e, 0x7c,
	0x51, 0x3c, 0x60, 0x3f, 0x17, 0xeb, 0x83, 0x7d, 0x9b, 0xc4, 0x06, 0xf6, 0xbb, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xa7, 0x55, 0x74, 0xa5, 0x0a, 0x01, 0x00, 0x00,
}
