component: artifacts

replicaCount: 1
logging: DEBUG

image:
  repository: hyperledger/fabric-tools
  pullPolicy: IfNotPresent
  tag: 2.0.0

domain: chainmetric.network

config:
  orderer:
    name: Orderer
    type: etcdraft
    mspID: orderer
    hostname: orderer
    port: 7050
    profile: OrdererGenesis
    channelID: system-channel
  organizations:
    - name: org1
      mspID: org1
      hostname: org1
      peers:
        - hostname: peer0
          port: 7051
      channelProfile: SupplyChannel
      channelID: supply-channel
  channels:
    - name: SupplyChannel
      profile: SupplyChannel
      channelID: supply-channel
      consortium: SupplyConsortium
      organizations:
        - org1
  crypto: |
  configtx: |


storageClass: local-path
