api:
  wallet_path: data/wallet
  organization: chipa-inu
  connection_config_path: ./connection.yaml
  grpc_tls_cert: data/certs/grpc/server.crt
  grpc_tls_key: data/certs/grpc/server.key
  jwt_signing_key: data/certs/jwt/jwt-key.pem
  jwt_private_key: data/certs/jwt/jwt-key.pem

mongo_auth: false
mongo_username: root
mongo_password: example

