project: chainmetric
component: chaincode

logging: DEBUG

image:
  repository: chainmetric/assets-contract
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 7052

persistence:
  enabled: true
  storageClass: longhorn
  path: /app/storage

org:
peer:
chaincode:
ccid:
