project: chainmetric
component: chaincode

logging: DEBUG

image:
  repository: chainmetric/smartcontracts/assets
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7052

persistence:
  enabled: true
  storageClass: local-path
  path: /app/storage

org:
peer:
chaincode:
ccid:
