// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requirement.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Requirement struct {
	UniqueID             string   `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	Property             string   `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	MinThreshold         float32  `protobuf:"fixed32,3,opt,name=minThreshold,proto3" json:"minThreshold,omitempty"`
	MaxThreshold         float32  `protobuf:"fixed32,4,opt,name=maxThreshold,proto3" json:"maxThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b809697927d7988, []int{0}
}

func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (m *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(m, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *Requirement) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *Requirement) GetMinThreshold() float32 {
	if m != nil {
		return m.MinThreshold
	}
	return 0
}

func (m *Requirement) GetMaxThreshold() float32 {
	if m != nil {
		return m.MaxThreshold
	}
	return 0
}

type RequirementInput struct {
	Property             string   `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	MinThreshold         float32  `protobuf:"fixed32,3,opt,name=minThreshold,proto3" json:"minThreshold,omitempty"`
	MaxThreshold         float32  `protobuf:"fixed32,4,opt,name=maxThreshold,proto3" json:"maxThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequirementInput) Reset()         { *m = RequirementInput{} }
func (m *RequirementInput) String() string { return proto.CompactTextString(m) }
func (*RequirementInput) ProtoMessage()    {}
func (*RequirementInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b809697927d7988, []int{1}
}

func (m *RequirementInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequirementInput.Unmarshal(m, b)
}
func (m *RequirementInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequirementInput.Marshal(b, m, deterministic)
}
func (m *RequirementInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequirementInput.Merge(m, src)
}
func (m *RequirementInput) XXX_Size() int {
	return xxx_messageInfo_RequirementInput.Size(m)
}
func (m *RequirementInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RequirementInput.DiscardUnknown(m)
}

var xxx_messageInfo_RequirementInput proto.InternalMessageInfo

func (m *RequirementInput) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *RequirementInput) GetMinThreshold() float32 {
	if m != nil {
		return m.MinThreshold
	}
	return 0
}

func (m *RequirementInput) GetMaxThreshold() float32 {
	if m != nil {
		return m.MaxThreshold
	}
	return 0
}

type RequirementFilter struct {
	UniqueID             string   `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequirementFilter) Reset()         { *m = RequirementFilter{} }
func (m *RequirementFilter) String() string { return proto.CompactTextString(m) }
func (*RequirementFilter) ProtoMessage()    {}
func (*RequirementFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b809697927d7988, []int{2}
}

func (m *RequirementFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequirementFilter.Unmarshal(m, b)
}
func (m *RequirementFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequirementFilter.Marshal(b, m, deterministic)
}
func (m *RequirementFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequirementFilter.Merge(m, src)
}
func (m *RequirementFilter) XXX_Size() int {
	return xxx_messageInfo_RequirementFilter.Size(m)
}
func (m *RequirementFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequirementFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RequirementFilter proto.InternalMessageInfo

func (m *RequirementFilter) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func init() {
	proto.RegisterType((*Requirement)(nil), "model.Requirement")
	proto.RegisterType((*RequirementInput)(nil), "model.RequirementInput")
	proto.RegisterType((*RequirementFilter)(nil), "model.RequirementFilter")
}

func init() { proto.RegisterFile("requirement.proto", fileDescriptor_6b809697927d7988) }

var fileDescriptor_6b809697927d7988 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4a, 0x2d, 0x2c,
	0xcd, 0x2c, 0x4a, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xea, 0x65, 0xe4, 0xe2, 0x0e, 0x42, 0x48, 0x0a, 0x49, 0x71, 0x71,
	0x94, 0xe6, 0x65, 0x16, 0x96, 0xa6, 0x7a, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1,
	0xf9, 0x20, 0xb9, 0x82, 0xa2, 0xfc, 0x82, 0xd4, 0xa2, 0x92, 0x4a, 0x09, 0x26, 0x88, 0x1c, 0x8c,
	0x2f, 0xa4, 0xc4, 0xc5, 0x93, 0x9b, 0x99, 0x17, 0x92, 0x51, 0x94, 0x5a, 0x9c, 0x91, 0x9f, 0x93,
	0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x14, 0x84, 0x22, 0x06, 0x56, 0x93, 0x58, 0x81, 0x50, 0xc3,
	0x02, 0x55, 0x83, 0x24, 0xa6, 0x54, 0xc6, 0x25, 0x80, 0xe4, 0x1c, 0xcf, 0xbc, 0x82, 0xd2, 0x12,
	0xba, 0xd8, 0xab, 0xcf, 0x25, 0x88, 0x64, 0xaf, 0x5b, 0x66, 0x4e, 0x49, 0x6a, 0x11, 0xbe, 0xc0,
	0x70, 0x12, 0x89, 0x12, 0x42, 0x0a, 0xd4, 0x62, 0x7d, 0x70, 0x70, 0x26, 0xb1, 0x81, 0x03, 0xd7,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x38, 0x67, 0xf0, 0x71, 0x01, 0x00, 0x00,
}
