// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: identity/api/presenter/access.proto

package presenter

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FabricCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Passcode string `protobuf:"bytes,2,opt,name=passcode,proto3" json:"passcode,omitempty"`
}

func (x *FabricCredentialsRequest) Reset() {
	*x = FabricCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_api_presenter_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FabricCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricCredentialsRequest) ProtoMessage() {}

func (x *FabricCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_api_presenter_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricCredentialsRequest.ProtoReflect.Descriptor instead.
func (*FabricCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_identity_api_presenter_access_proto_rawDescGZIP(), []int{0}
}

func (x *FabricCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FabricCredentialsRequest) GetPasscode() string {
	if x != nil {
		return x.Passcode
	}
	return ""
}

type FabricCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret         *VaultSecret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	ApiAccessToken string       `protobuf:"bytes,2,opt,name=apiAccessToken,proto3" json:"apiAccessToken,omitempty"`
	User           *User        `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *FabricCredentialsResponse) Reset() {
	*x = FabricCredentialsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_api_presenter_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FabricCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricCredentialsResponse) ProtoMessage() {}

func (x *FabricCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_api_presenter_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricCredentialsResponse.ProtoReflect.Descriptor instead.
func (*FabricCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_identity_api_presenter_access_proto_rawDescGZIP(), []int{1}
}

func (x *FabricCredentialsResponse) GetSecret() *VaultSecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *FabricCredentialsResponse) GetApiAccessToken() string {
	if x != nil {
		return x.ApiAccessToken
	}
	return ""
}

func (x *FabricCredentialsResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type VaultSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path  string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *VaultSecret) Reset() {
	*x = VaultSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_api_presenter_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecret) ProtoMessage() {}

func (x *VaultSecret) ProtoReflect() protoreflect.Message {
	mi := &file_identity_api_presenter_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecret.ProtoReflect.Descriptor instead.
func (*VaultSecret) Descriptor() ([]byte, []int) {
	return file_identity_api_presenter_access_proto_rawDescGZIP(), []int{2}
}

func (x *VaultSecret) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VaultSecret) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CertificateAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate []byte `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	SigningKey  []byte `protobuf:"bytes,3,opt,name=signingKey,proto3" json:"signingKey,omitempty"`
}

func (x *CertificateAuthRequest) Reset() {
	*x = CertificateAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_api_presenter_access_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateAuthRequest) ProtoMessage() {}

func (x *CertificateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_api_presenter_access_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateAuthRequest.ProtoReflect.Descriptor instead.
func (*CertificateAuthRequest) Descriptor() ([]byte, []int) {
	return file_identity_api_presenter_access_proto_rawDescGZIP(), []int{3}
}

func (x *CertificateAuthRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertificateAuthRequest) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type CertificateAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiAccessToken string `protobuf:"bytes,1,opt,name=apiAccessToken,proto3" json:"apiAccessToken,omitempty"`
	User           *User  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CertificateAuthResponse) Reset() {
	*x = CertificateAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_api_presenter_access_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateAuthResponse) ProtoMessage() {}

func (x *CertificateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_api_presenter_access_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateAuthResponse.ProtoReflect.Descriptor instead.
func (*CertificateAuthResponse) Descriptor() ([]byte, []int) {
	return file_identity_api_presenter_access_proto_rawDescGZIP(), []int{4}
}

func (x *CertificateAuthResponse) GetApiAccessToken() string {
	if x != nil {
		return x.ApiAccessToken
	}
	return ""
}

func (x *CertificateAuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_identity_api_presenter_access_proto protoreflect.FileDescriptor

var file_identity_api_presenter_access_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x1a, 0x21, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5e, 0x0a, 0x18, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x60, 0x01, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x20, 0x08, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0xc7, 0x01, 0x0a, 0x19, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x70,
	0x69, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x38, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x3a, 0x03, 0x80, 0x43, 0x01, 0x22, 0x3c, 0x0a, 0x0b, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x3a, 0x03, 0x80, 0x43, 0x01, 0x22, 0x6c, 0x0a, 0x16, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x7a, 0x02, 0x10,
	0x64, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x27,
	0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x7a, 0x02, 0x10, 0x19, 0x52, 0x0a, 0x73, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x22, 0x80, 0x01, 0x0a, 0x17, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x70, 0x69,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x38, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x3a, 0x03, 0x80, 0x43, 0x01, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6d, 0x6f, 0x74, 0x68, 0x2d,
	0x79, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_identity_api_presenter_access_proto_rawDescOnce sync.Once
	file_identity_api_presenter_access_proto_rawDescData = file_identity_api_presenter_access_proto_rawDesc
)

func file_identity_api_presenter_access_proto_rawDescGZIP() []byte {
	file_identity_api_presenter_access_proto_rawDescOnce.Do(func() {
		file_identity_api_presenter_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_identity_api_presenter_access_proto_rawDescData)
	})
	return file_identity_api_presenter_access_proto_rawDescData
}

var file_identity_api_presenter_access_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_identity_api_presenter_access_proto_goTypes = []interface{}{
	(*FabricCredentialsRequest)(nil),  // 0: chainmetric.identity.presenter.FabricCredentialsRequest
	(*FabricCredentialsResponse)(nil), // 1: chainmetric.identity.presenter.FabricCredentialsResponse
	(*VaultSecret)(nil),               // 2: chainmetric.identity.presenter.VaultSecret
	(*CertificateAuthRequest)(nil),    // 3: chainmetric.identity.presenter.CertificateAuthRequest
	(*CertificateAuthResponse)(nil),   // 4: chainmetric.identity.presenter.CertificateAuthResponse
	(*User)(nil),                      // 5: chainmetric.identity.presenter.User
}
var file_identity_api_presenter_access_proto_depIdxs = []int32{
	2, // 0: chainmetric.identity.presenter.FabricCredentialsResponse.secret:type_name -> chainmetric.identity.presenter.VaultSecret
	5, // 1: chainmetric.identity.presenter.FabricCredentialsResponse.user:type_name -> chainmetric.identity.presenter.User
	5, // 2: chainmetric.identity.presenter.CertificateAuthResponse.user:type_name -> chainmetric.identity.presenter.User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_identity_api_presenter_access_proto_init() }
func file_identity_api_presenter_access_proto_init() {
	if File_identity_api_presenter_access_proto != nil {
		return
	}
	file_identity_api_presenter_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_identity_api_presenter_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FabricCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_api_presenter_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FabricCredentialsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_api_presenter_access_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_api_presenter_access_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificateAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_api_presenter_access_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificateAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_identity_api_presenter_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_api_presenter_access_proto_goTypes,
		DependencyIndexes: file_identity_api_presenter_access_proto_depIdxs,
		MessageInfos:      file_identity_api_presenter_access_proto_msgTypes,
	}.Build()
	File_identity_api_presenter_access_proto = out.File
	file_identity_api_presenter_access_proto_rawDesc = nil
	file_identity_api_presenter_access_proto_goTypes = nil
	file_identity_api_presenter_access_proto_depIdxs = nil
}
