apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hosting.service }}-{{ .Values.hosting.organization | replace "." "-" }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ .Values.hosting.service }}.{{ .Values.hosting.organization }}"
