{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
  {{- toYaml .Values.ingress.entrypoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.hosting.service }}.{{ .Values.hosting.organization}}.{{ .Values.hosting.domain }}`)
      kind: Rule
      services:
        - name: {{ .Values.hosting.service }}-{{ .Values.hosting.organization | replace "." "-" }}
          port: {{ .Values.service.port }}
          scheme: https
  {{- if .Values.ingress.tls.enabled }}
  tls:
    certResolver: {{ .Values.ingress.tls.certResolver }}
  {{- end }}
{{- end }}
