project: chainmetric

ingressroutes:
  - name: traefik-dashboard
    domain: timoth.io
    serviceHostname: traefik.dev
    entrypoints:
      - web
      - websecure
    service:
      name: api@internal
      kind: TraefikService
      port: 8080
      scheme: http
    # - name: traefik-auth
    tls:
      enabled: true
      certResolver: le
#  - name: vault
#    domain: timoth.io
#    serviceHostname: vault.infra
#    entrypoints:
#      - web
#      - websecure
#    service:
#      name: vault
#      kind: Service
#      port: 8200
#      scheme: http
#    tls:
#      enabled: true
#      certResolver: le
  - name: longhorn
    domain: timoth.io
    serviceHostname: longhorn.dev
    entrypoints:
      - web
      - websecure
    service:
      name: longhorn-frontend
      kind: Service
      port: 80
      scheme: http
    tls:
      enabled: true
      certResolver: le
    namespace: longhorn-system
