project: chainmetric
component: api-service

logging: DEBUG

deployement:
  replicaCount: 1

image:
  repository: chainmetric/api.identity
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8080

externalAccess:
  enabled: true
  domain: chainmetric.network
  ownershipMsp: chipa-inu.org
  serviceHostname: identity
  taefik:
    entrypoints:
      - web
      - websecure
    tls:
      enabled: true
      certResolver: le

persistence:
  enabled: true
  storageClass: local-path
  path: /app/data

serviceAccount:
  create: true
  name: ""
  annotations: {}

volumes:
  - type: secret
    name: identity-chipa-inu-org-hlf-connection
    mountPath: /app/config
  - type: secret
    name: identity.chipa-inu.org.chainmetric.network-tls
    mountPath: /app/certs/grpc
  - type: secret
    name: identity-chipa-inu-org-jwt-keys
    mountPath: /app/certs/jwt
  - type: claim
    name: artifacts.pvc
    mountPath: /app/crypto

envs:
  - type: secret
    name: VAULT_TOKEN
    secretName: vault-credentials
    secretKey: token
