project: chainmetric
component: api-service

logging: DEBUG

replicaCount: 1

image:
  repository: chainmetric/api.identity
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 8080

hosting:
  domain: chainmtric.network
  organization: chipa-inu-org
  service: identity

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le

persistence:
  enabled: true
  storageClass: local-path
  path: app/data

serviceAccount:
  create: true
  annotations: {}
  name: ""

config:
  path: app/config
