architecture: standalone

image:
  repository: arm64v8/mongo
  tag: 4.4.8

readinessProbe:
  enabled: false

persistence:
  storageClass: longhorn
  mountPath: /data/db
  size: 1Gi

auth:
  enabled: false
  database: chainmetric
  username: chainmetric_admin
